# Generated by Django 5.2.8 on 2025-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='brand',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST registration number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Locked balance for active campaigns', max_digits=10),
        ),
        migrations.AddField(
            model_name='brand',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Main wallet balance for brand', max_digits=10),
        ),
    ]
