# Generated by Django 5.2.8 on 2025-11-19 00:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/')),
                ('additional_images', models.JSONField(blank=True, default=list)),
                ('product_url', models.URLField(help_text="Link to product on brand's website/store")),
                ('review_platform', models.CharField(choices=[('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('SHOPIFY', 'Shopify Store'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_amount', models.DecimalField(decimal_places=2, help_text='Cashback amount for completing this review', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('min_review_rating', models.IntegerField(default=3, help_text='Minimum rating required for review', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_deadline_days', models.IntegerField(default=7, help_text='Number of days user has to submit review after order approval', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_slots', models.PositiveIntegerField(default=1, help_text='Total number of slots available')),
                ('reserved_slots', models.PositiveIntegerField(default=0, help_text='Number of slots currently reserved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_slots', to='marketplace.product')),
            ],
            options={
                'verbose_name': 'Review Slot',
                'verbose_name_plural': 'Review Slots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='marketplace_brand_i_a0a3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='marketplace_is_feat_f4221d_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewslot',
            index=models.Index(fields=['product', 'status'], name='marketplace_product_1a7d69_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewslot',
            index=models.Index(fields=['status', 'expires_at'], name='marketplace_status_9d8af7_idx'),
        ),
    ]
