# Generated by Django 5.2.8 on 2025-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, help_text='Amazon Standard Identification Number', max_length=50, null=True),
        ),
    ]
