# Generated by Django 5.2.8 on 2025-11-19 00:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Order ID from the purchase platform', max_length=200)),
                ('order_date', models.DateField(help_text='Date when the order was placed')),
                ('order_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('purchase_proof', models.ImageField(help_text='Screenshot or image of purchase confirmation', upload_to='orders/proofs/')),
                ('additional_proof', models.ImageField(blank=True, help_text='Additional proof if needed', null=True, upload_to='orders/proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if order is rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.product')),
                ('review_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.reviewslot')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'), models.Index(fields=['product', 'status'], name='orders_orde_product_fd7edb_idx'), models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx')],
            },
        ),
    ]
