# Generated by Django 5.2.8 on 2025-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clicked_at',
            field=models.DateTimeField(blank=True, help_text="When user clicked 'Buy Now'", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft submission before proof upload'),
        ),
    ]
